// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwp3FSeBNFO8AK2moezpAKE6PIWDRfFPQ',
    appId: '1:142980092276:web:436c9dcfd6dc6a4c34dc21',
    messagingSenderId: '142980092276',
    projectId: 'flutter-task-manager-8d476',
    authDomain: 'flutter-task-manager-8d476.firebaseapp.com',
    storageBucket: 'flutter-task-manager-8d476.firebasestorage.app',
    measurementId: 'G-YH1NSJ0HNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh5gVM5Sq8xBKvrSn_9YkCSUEuFkY9aUo',
    appId: '1:142980092276:android:723fa66ac253582d34dc21',
    messagingSenderId: '142980092276',
    projectId: 'flutter-task-manager-8d476',
    storageBucket: 'flutter-task-manager-8d476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLoqx4o3btd1YznhdPPKsIZ93y1jo0MCg',
    appId: '1:142980092276:ios:0aab8323ca62875634dc21',
    messagingSenderId: '142980092276',
    projectId: 'flutter-task-manager-8d476',
    storageBucket: 'flutter-task-manager-8d476.firebasestorage.app',
    iosBundleId: 'com.example.flutterTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLoqx4o3btd1YznhdPPKsIZ93y1jo0MCg',
    appId: '1:142980092276:ios:0aab8323ca62875634dc21',
    messagingSenderId: '142980092276',
    projectId: 'flutter-task-manager-8d476',
    storageBucket: 'flutter-task-manager-8d476.firebasestorage.app',
    iosBundleId: 'com.example.flutterTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwp3FSeBNFO8AK2moezpAKE6PIWDRfFPQ',
    appId: '1:142980092276:web:ac94fe7331d6bbdc34dc21',
    messagingSenderId: '142980092276',
    projectId: 'flutter-task-manager-8d476',
    authDomain: 'flutter-task-manager-8d476.firebaseapp.com',
    storageBucket: 'flutter-task-manager-8d476.firebasestorage.app',
    measurementId: 'G-4KMPBE7LFV',
  );
}
